overrides = [{ "files" = "*.svelte", "options" = { "parser" = "svelte" } }]
useTabs = false
singleQuote = true
trailingComma = "none"
printWidth = 100
proseWrap = "always"
plugins = ["prettier-plugin-svelte"]
semi = false
