#:schema ../../../post.schema.json
title = "Test Post"

[manifest]
date = 2024-04-12T20:48:40.799Z
authors = ["Youwen Wu"]
blurb = "A display of all the blog's rendering capabilities!"
description = "A blog post to test all of the rendering capabilities, with remarks on the side."
type = "article"
highlight = true

[manifest.tags]
primary = ["test", "first post", "formatting"]
secondary = ["blog", "placeholder"]

[cover]
src = "https://images.unsplash.com/photo-1712230879699-e8a0a389da63?q=80&w=3132&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
alt = "A beautiful landscape"
caption = "This is the first post! (image courtesy of unsplash)"
